name: API CI

#on: push
#on: [push, XXX]
on:
  push:
    branches:
      - "feature/*"
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - "main"

jobs:
  check_pr:
    runs-on: ubuntu-latest
    name: Check if feature has been merge onto the develop branch

    steps:
      # Checkout the branch
      - name: fetch it all
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get merged branches
        run: |
          echo ${GITHUB_HEAD_REF##*/}
          if [ "$(git branch -r --merged origin/develop origin/feature/${GITHUB_HEAD_REF##*/})" != "origin/feature/${GITHUB_HEAD_REF##*/}" ]; then
            echo "The current Pull Request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          else
            echo "The branch feature/${GITHUB_REF##*/} is allowed to be merged into master"
            exit 0
          fi