name: API CI

#on: push
#on: [push, XXX]
on:
#  push:
#    branches:
#      - "feature/*"
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - "main"
      - "feature/*"


jobs:
  check_pr:
    runs-on: ubuntu-latest
    name: Check if feature has been merge onto the develop branch

    steps:
      # Checkout the branch
      - name: fetch it all
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get merged branches
        run: |
          echo "1" ${GITHUB_HEAD_REF##*/}
          echo "2" ${GITHUB_REF##*/}
          echo "3" $(git branch -r --merged origin/develop origin/feature/${GITHUB_HEAD_REF##*/})
          echo "4" $(git branch -r --merged origin/develop)
          echo "5" origin/feature/${GITHUB_HEAD_REF##*/}
          echo "6" $(git branch -r --no-merged origin/develop)
          
          
          echo "7" $(git branch -r --no-merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/})
          if $(git branch -r --no-merged origin/develop | grep "origin/feature/${GITHUB_HEAD_REF##*/}") == "origin/feature/${GITHUB_HEAD_REF##*/}" then echo "branche trouvée donc pas bon"; else echo "branche pas trouvée donc OK"; fi
          
          if [ "$(git branch -r --no-merged origin/develop | grep "origin/feature/${GITHUB_HEAD_REF##*/}")" == "origin/feature/${GITHUB_HEAD_REF##*/}" ]; then
            echo "The current Pull Request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          else
            echo "The branch feature/${GITHUB_REF##*/} is allowed to be merged into master since it has already been merged into develop"
            exit 0
          fi

#          if [ "$(git branch -r --merged origin/develop origin/feature/${GITHUB_HEAD_REF##*/})" != "origin/feature/${GITHUB_HEAD_REF##*/}" ]; then
#            echo "The current Pull Request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
#            exit 1
#          else
#            echo "The branch feature/${GITHUB_REF##*/} is allowed to be merged into master"
#            exit 0
#          fi