name: DeleteArtifacts

on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  delete_artifacts:
    runs-on: ubuntu-latest
    name: Once the PR has been merged, delete the artifacts
    steps:
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main_pull_request_ci.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: ""
          name: workflow_run_id

      - name: Read artifacts
        run: |
          WORKFLOW_RUN_ID = cat pr_number_${{ github.event.number }}_workflow_run_id.txt


      - name: Delete artifacts
        run: |
          node delete_artifact.js $WORKFLOW_RUN_ID
          
