name: DevelopCI

on:
  pull_request:
    types: [closed ]
    branches:
      - develop

jobs:
  dev_tests_run:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Unit tests
        run: |
          echo "Unit testing"
      - name: Integration tests
        run: |
          echo "Integration testing"

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/pr_number.txt
      - uses: actions/upload-artifact@v3
        with:
            name: pr_number
            path: pr/