name: DevelopCI

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - develop


jobs:
  dev_tests_run:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - name: Run unit tests
        run: |
          echo "running unit tests"

  dev_integration_tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run integration tests
    steps:
      - name: integration tests
        run: |
          echo "running integration tests"