name: DevelopCI
#Add comment to differentiate from dev and main
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - develop

jobs:
  dev_tests_run:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Unit tests
        run: |
          echo "Unit testing"
          
  dev_integration_tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - name: Integration tests
        run: |
          echo "Integration testing"