name: DevelopCI

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - develop


jobs:
  dev_tests_run:
#    if: github.event.pull_request.merge == 'False'
    runs-on: ubuntu-latest
    name: Update main's current PR

    steps:
      - name: tests
        run: echo "test DevelopCI en cours"