name: DevelopCI

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  dev_tests_run:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Unit tests
        run: |
          echo "Unit testing"
      - name: Integration tests
        run: |
          echo "Integration testing"

  check_artifact:
    needs: [dev_tests_run]
    runs-on: ubuntu-latest
    name: Verify pr_number
    steps:
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main_write_entry_pr_list_ci.yml
          workflow_conclusion: ""
          name: pr_list
          if_no_artifact_found: warn

      - name: Read artifacts
        id: set-pr-number
        run: |
          echo "PR_NUMBER=$(cat ./pr_list.txt | grep ${{ github.event.pull_request.head.sha }}: | rev | cut -d: -f 1 | rev)" >> $GITHUB_OUTPUT
      - name: use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: run script to update MainPRCI
        run: |
          npm install @actions/github
          node updatePR.js ${{ steps.set-pr-number.outputs.PR_NUMBER }} ${{ secrets.TOKEN_ACCESS }}