name: DevelopCI

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - develop


#If a PR has been refused on main, the developer is going to make new commits to the develop branch.
#From then, when new commit/PR are added onto develop, the "main" PR has to be updated and ran once more

jobs:
  update_main_pr:
    runs-on: ubuntu-latest
    name: Update main's current PR

    steps:
      - name: tests
        run: echo "test en cours"


# a little comment to disrupt my whole world, I'll probably need a fixme right after I commit this shit 

# again some shit