name: DevelopArtifactCI

on:
  #  Will only run when a workflow named DevelopCI runs on a branch named "develop"
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]
    branches: [develop]

env:
  TEST_SUCCESS: ${{ github.event.workflow_run.conclusion == 'success' }}
jobs:
  write_artifact_on_dev_tests_failure:
    runs-on: ubuntu-latest
    name: Write an artifact
    steps:
      #      As Boolean, if test have passed then <true> else <false>
      - name: Upload test results to artifact
        run: |
          mkdir -p ./test-results/test-artifact.txt
          echo $TEST_SUCCESS > ./test-results/test-artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: test-results-artifact
          path: .test-results/test-artifact.txt