name: DevelopCI

on:
  pull_request:
    types: [closed ]
    branches:
      - develop

jobs:
  dev_tests_run:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Unit tests
        run: |
          echo "Unit testing"
      - name: Integration tests
        run: |
          echo "Integration testing"

