name: FeatureCI

on:
    push:
      branches:
        - "feature/*"

jobs:
  tests_run:
    runs-on: ubuntu-latest
    name: Run feature tests

    steps:
      - name: tests
        run: echo "test feature en cours"