name: MainDownloadArtifactCI

on:
  workflow_run:
    workflows: [ DevelopArtifactCI ]
    types: [ completed ]

jobs:
  check_for_validated_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Download an artifact
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
#          branch: develop
#          name: test-results-artifact
        run: |
          cat test-results-artifact/test-artifact.txt
          if [ cat test-artifact.txt == false ]; then
            exit 1
          else
            exit 0
          fi
