name: MainPRCI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
jobs:
  check_feature_merged:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    name: Check if feature has been merge onto the develop branch
    steps:
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get merged branches
        run: |
          echo $(git branch -r --merged origin/develop)
          if [ $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) ]; then
            echo "The branch origin/feature/${GITHUB_HEAD_REF##*/} is allowed to be merged into master since it has already been merged into develop"
            exit 0
          else
            echo "The current pull request is not allowed as the origin/feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          fi

      - name: Write pr_number to file
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/pr_number.txt
          echo ${GITHUB_REF##*/} > ./pr/github_ref.txt
          echo ${GITHUB_HEAD_REF##*/} > ./pr/github_head_ref.txt
      - uses: actions/upload-artifact@v3
        with:
            name: pr_number
            path: pr/