name: MainUpdateFromDevCI

on:
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]

jobs:
  update_pull_request_from_dev_if:
    runs-on: ubuntu-latest
    name: Check if feature is still compliant with requirements on main
    steps:
      - name: check developCI passed
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            exit 0
          else 
            exit 1
          fi

      - name: use Node.js v12
        uses: actions/setup-node@v1
        with:
            node-version: 12

      - uses: actions/checkout@v2
        name: checkout
#        with:
#          fetch-depth: 0

      - uses: ./github/actions
        name: Download artifact
        with:
          workflow: develop_ci.yml
          workflow_conclusion: success
          name: pr_number
          search_artifacts: true

#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: pr_number
#          path: ./pr/
#
#      - name: Display content of test-artifact
#        run: |
#          cat pr_number
#          cat pr_number.txt
#          cat pr_number_bis.txt
#          cat pr_number_third.txt
#          PR_NUMBER=pr_number
#          PR_NUMBER_BIS=pr_number.txt
#          echo $PR_NUMBER
#          echo $PR_NUMBER_BIS
#        working-directory: ./pr/pr_number.txt
#
#      - name: run script to update MainPRCI
#        run: |
#          npm install @actions/github
#          node updatePR.js ${PR_NUMBER}