name: MainUpdateFromDevCI

on:
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]

jobs:
  update_pull_request_from_dev_if:
    runs-on: ubuntu-latest
    name: Check if feature is still compliant with requirements on main
    steps:
      - name: check developCI passed
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            exit 0
          else 
            exit 1
          fi

      - name: use Node.js v12
        uses: actions/setup-node@v1
        with:
            node-version: 12

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: develop_ci.yml
          workflow_conclusion: success
          name: pr_number
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts: false
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: true
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: fail

#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: pr_number
#          path: ./pr/
#
#      - name: Display content of test-artifact
#        run: |
#          cat pr_number
#          cat pr_number.txt
#          cat pr_number_bis.txt
#          cat pr_number_third.txt
#          PR_NUMBER=pr_number
#          PR_NUMBER_BIS=pr_number.txt
#          echo $PR_NUMBER
#          echo $PR_NUMBER_BIS
#        working-directory: ./pr/pr_number.txt

      - name: run script to update MainPRCI
        run: |
          npm install @actions/github
          node updatePR.js ${PR_NUMBER}
