name: MainUpdateFromDevCI

on:
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]

jobs:
  update_pull_request_from_dev_if:
    runs-on: ubuntu-latest
    name: Check if feature is still compliant with requirements on main
    steps:
      - name: check developCI passed
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            exit 0
          else 
            exit 1
          fi
#       trigger MainPRCI
      - name: run script to update MainPRCI
        run: node updatePR.js