name: MainUpdateFromDevCI

on:
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]

jobs:
  update_pull_request_from_dev_if:
    runs-on: ubuntu-latest
    name: When feature is merged on develop, check if feature is still compliant with requirements on main
    steps:
      - name: Check DevelopCI is successfull
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            exit 0
          else 
            exit 1
          fi

      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main_write_entry_pr_list_ci.yml
          workflow_conclusion: ""
          name: pr_list

      - name: Read artifacts
        run: |
          PR_NUMBER=$(cat pr_list | grep ${{ github.sha }}: | rev | cut -d: -f 1 | rev)

      - name: use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: run script to update MainPRCI
        run: |
          npm install @actions/github
          node updatePR.js ${PR_NUMBER} ${{ secrets.TOKEN_ACCESS }}