name: MainUpdateFromDevCI

on:
  workflow_run:
    workflows: [DevelopCI]
    types: [completed]

jobs:
  update_pull_request_from_dev_if:
    runs-on: ubuntu-latest
    name: Check if feature is still compliant with requirements on main
    steps:
      - name: check developCI passed
        run: |
          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
            exit 0
          else 
            exit 1
          fi
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check feature has been merged
        run: |
          echo "running test on main if DevelopCI has passed"
          echo origin/feature/${GITHUB_HEAD_REF##*/}
          echo $(git branch -r --merged origin/develop)
          if [ $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) && $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) != origin/feature/]; then
            echo "The branch feature/${GITHUB_HEAD_REF##*/} is allowed to be merged into master since it has already been merged into develop"
            exit 0
          else
            echo "The current pull request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          fi