name: MainWriteToPrListCI

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  check_feature_merged:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    name: On pull_request creation, delete old pr_list file and append its data into new pr_list file
    steps:
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main_write_entry_pr_list_ci.yml
          workflow_conclusion: ""
          name: pr_list
          if_no_artifact_found: warn

      - name: Write commit:pr_number and pr_list history to file
        run: |
          if [[ -f "./pr_list/pr_list.txt" ]]; then
            CURRENT_PR_LIST=$(cat ./pr_list/pr_list.txt)
            rm -rf ./pr_list
            mkdir -p ./pr_list
            echo $CURRENT_PR_LIST >> ./pr_list/pr_list.txt
            echo ${{ github.sha }}:${{ github.event.number }} >> ./pr_list/pr_list.txt
          fi

      - name: use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Delete old artifact
        run: |
          npm install @actions/github
          node delete_artifact.js ${{ secrets.TOKEN_ACCESS }}

      - name: Upload updated artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_list
          path: ./pr_list