name: Main_from_dev_PR_CI

on: 
  workflow_run:
    workflows: [DevelopCI]
    types:
      - completed
    branches:
      - main

jobs:
  update_pull_request_from_dev_if:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    name: Check if feature is still compliant with requirements on main
    steps:
      - name: run test
        run: |
          echo "running test on main if DevelopCI has passed"
          origin/feature/${GITHUB_HEAD_REF##*/}
          if [ $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) != origin/feature/${GITHUB_HEAD_REF##*/} && $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) != origin/feature/]; then
            echo "The current pull request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          else
            echo "The branch feature/${GITHUB_HEAD_REF##*/} is allowed to be merged into master since it has already been merged into develop"
            exit 0
          fi