name: Main_PR_CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
        
jobs:      
  check_pull_request_if_opened:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    name: Check if feature has been merge onto the develop branch
    steps:
      - name: Fetch all branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get merged branches
        run: |
          echo origin/feature/${GITHUB_HEAD_REF##*/}
          echo $(git branch -r --merged origin/develop)
          if [ $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) && $(git branch -r --merged origin/develop | grep origin/feature/${GITHUB_HEAD_REF##*/}) != origin/feature/]; then
            echo "The branch feature/${GITHUB_HEAD_REF##*/} is allowed to be merged into master since it has already been merged into develop"
            exit 0
          else
            echo "The current pull request is not allowed as the feature/${GITHUB_HEAD_REF##*/} has not been merge into develop yet"
            exit 1
          fi